<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'fkooman\\secookie\\cookie' => '/../src/Cookie.php',
                'fkooman\\secookie\\cookieinterface' => '/../src/CookieInterface.php',
                'fkooman\\secookie\\exception\\cookieexception' => '/../src/Exception/CookieException.php',
                'fkooman\\secookie\\exception\\sessionexception' => '/../src/Exception/SessionException.php',
                'fkooman\\secookie\\headerinterface' => '/../src/HeaderInterface.php',
                'fkooman\\secookie\\phpheader' => '/../src/PhpHeader.php',
                'fkooman\\secookie\\session' => '/../src/Session.php',
                'fkooman\\secookie\\sessioninterface' => '/../src/SessionInterface.php',
                'fkooman\\secookie\\tests\\cookietest' => '/../tests/CookieTest.php',
                'fkooman\\secookie\\tests\\sessiontest' => '/../tests/SessionTest.php',
                'fkooman\\secookie\\tests\\testheader' => '/../tests/TestHeader.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
