<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'fkooman\\secookie\\cookie' => '/Cookie.php',
                'fkooman\\secookie\\cookieinterface' => '/CookieInterface.php',
                'fkooman\\secookie\\exception\\cookieexception' => '/Exception/CookieException.php',
                'fkooman\\secookie\\exception\\sessionexception' => '/Exception/SessionException.php',
                'fkooman\\secookie\\headerinterface' => '/HeaderInterface.php',
                'fkooman\\secookie\\phpheader' => '/PhpHeader.php',
                'fkooman\\secookie\\session' => '/Session.php',
                'fkooman\\secookie\\sessioninterface' => '/SessionInterface.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd


